spring:
  freemarker:
    tempalte-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  mvc:
    static-path-pattern: /**
server:
  port: 8080


caoyxRpc:
  register:
    type: zookeeper
    address: 127.0.0.1:2181
